docs = {"pycord" : "https://docs.pycord.dev/en/stable/",
		"discord developpers" : "https://discord.com/developers/applications",
		"crontab" : "https://www.man7.org/linux/man-pages/man5/crontab.5.html",
		"cron" : "https://www.man7.org/linux/man-pages/man8/cron.8.html"}

bool_reac = {True : "<a:check:1164580201573912677>",
			False : "<a:denied:1164580451680256041>"}

cmds = {"aide" : ["Affiche la liste des commandes.", # ~ description
				"Everyone", # ~ permissions
				"Entrer la liste des commandes pour obtenir de l'aide, séparer par une virgule.", # ~ aide supplémentaire
				{"commande o" : "Une commande en particulier. 'aide' par défaut.",
				"visible o" : "Affiche la fenêtre d'aide à tout le monde. Désactivé par défaut."}], # ~ paramètres
		"dm" : ["Envoie un MP",
				"Développeur",
				"",
				{"" : ""}],
		"logout" : ["Déconnecte le bot.",
				"Développeur",
				"",
				{"" : ""}],
		"ping" : ["Ping et autres infos",
				"Everyone",
				"Informations : latence du bot, running time ... ce genre de trucs.",
				{"" : ""}],
		"poll" : ["Crée un sondage, séparer les réponses par un point virgule.",
				"Everyone",
				"",
				{"question" : "Question à poser dans le sondage.",
				"réponses" : "Réponses possibles dans le sondage, séparer par un point virgule.",
				"salon o" : "Salon où envoyer le sondage."}],
		"role_react" : ["Ajoute un menu déroulant à un message pour choisir des rôles.",
				"Gérer les rôles",
				"""`roles` et `message` n'ont pas besoin d'être renseignés tous les 2.
Dans le cas où `message_id` est renseigné, un nouveau message avec le même contenu sera envoyé et l'original sera supprimé.
Si échec suivi d'une possibilité `Actualiser`, choisir `Actualiser` et continuer normalement.""",
				{"roles" : "Mentions des rôles à attribuer, avec ou sans séparation.",
				"message o" : "Toutes les mentions des rôles à attribuer.",
				"message_id o" : "Identifiant d'un message à utiliser. ⚠ le message sera supprimé puis envoyé par le bot."}],
		"spam_emote" : ["Spamme une emote.",
				"Everyone",
				"",
				{"emote o" : "Une emote qui va être spam pour atteindre la limite de 2000 caractères.",
				"user o" : "Mentionne un utilisateur en particulier."}],
		"clear" : ["Nettoie un salon.",
				"Gérer les Messages",
				"Préciser le nombre de messages et le salon (par défaut : le salon actuel), éventuellement l'auteur.",
				{"nombre" : "Nombre de messages à chercher dans l'historique.",
				"salon o" : "Salon où supprimer les messages.",
				"user o" : "Ne supprimer que les messages de l'utilisateur en question."}],
		"ban" : ["Si tu sais pas ce que c'est, t'es pas concerné.",
				"Ban",
				"",
				{"user" : "Utilisateur à bannir.",
				"raison o" : "Motif du ban."}],
		"mute" : ["Mute une personne.",
				"Mute",
				"""Durée sous forme d'un nombre et `d` ou `j` (jour), `h` (heure), `m` (minute), `s` (secondes).
Ne pas combiner, par exemple `3m30s` est invalide, utilisez `210s`.""",
				{"user" : "Utilisateur à mute.",
				"durée o" : "Durée du mute (par defaut 30 minutes).",
				"raison o" : "Motif du mute."}],
		"invite" : ["Affiche un lien pour inviter le bot.",
				"Everyone",
				"",
				{"" : ""}],
		"code" : ["Lien vers GitHub pour accéder aux fichiers du bot.",
				"Everyone",
				f"""Doc Pycord : [ici]({docs['pycord']}).
Portail des Développeurs : [ici]({docs['discord developpers']}).
Doc Cron : [ici]({docs['crontab']}) et [là]({docs['cron']}).""",
				{"" : ""}],
		"get_logs" : ["Envoie les logs des erreurs.",
				"Développeur",
				"",
				{"last_x_lines o" : "Les X dernières lignes de stderr."}],
		"qpup" : ["Lance le quiz Questions Pour Un Poulet !",
				"Everyone",
				"Tellement de lore derrière ce nom ... Même avec le nom vous devinerez pas ...",
				{"nbquestions o" : "Nombre de questions désirées."}],
		"user_info" : ["Donne des informations sur la personne demandée.",
				"Everyone",
				"Nom, date de création du compte, membre du serveur depuis <date>, rôles (si permission `Gérer les Rôles`))",
				{"user" : "Utilisateur ciblé."}],
		"2048" : ["Démarre une partie de 2048.",
				"Everyone",
				"",
				{"size o" : "Taille de la grille (par défaut 4)."}],
		"suggestions" : ["Envoie un MP au dev à propos d'une suggestion que vous avez.",
				"Everyone",
				"Vous pouvze aussi passer par le Serveur de Support",
				{"" : ""}],
		"droprates" : ["Indique le nombre de lootbox attendu pour une certaine probabilité de drop.",
				"Everyone",
				"Renseigner le nom de la lootbox **et** l'item voulu va afficher la fenêtre de résultats à tout le monde.",
				{"pourcentage" : "Pourcentage de drop de l'item désiré.",
				"nom o" : "Nom de la lootbox.",
				"item o" : "Item désiré."}],
		"embed" : ["Crée un nouvel embed, entièrement customisable.",
				"Everyone",
				"Si modification d'un Embed existant : aucune modification n'est effective avant de valider à la toute fin.",
				{"edit" : "ID du message à modifier."}],
		"no_custom_messages" : ["Désactive les messages de réponses personnalisées sur ce serveur.",
				"Administrateur",
				"Désactive tout, pour en remettre seulement certaines en service, envoyer un MP au bot à ce sujet.",
				{"" : ""}]}
