docs = {"pycord" : "https://docs.pycord.dev/en/stable/",
		"discord developpers" : "https://discord.com/developers/applications",
		"crontab" : "https://www.man7.org/linux/man-pages/man5/crontab.5.html",
		"cron" : "https://www.man7.org/linux/man-pages/man8/cron.8.html"}

bool_reac = {True : "<a:check:1164580201573912677>",
			False : "<a:denied:1164580451680256041>"}

cmds = {"aide" : ["Affiche la liste des commandes", # ~ description
				"Everyone", # ~ permissions
				"Entrer la liste des commandes pour obtenir de l'aide, séparer par une virgule", # ~ aide supplémentaire
				{"commande o" : "Une ou plusieurs commande(s) en particulier, séparer par des ;",
				"visible o" : "Affiche la fenêtre d'aide à tout le monde, désactivé par défaut"}], # ~ paramètres
		"dm" : ["Envoie un MP",
				"Développeur",
				"",
				{"" : ""}],
		"logout" : ["Déconnecte le bot",
				"Développeur",
				"",
				{"" : ""}],
		"ping" : ["Ping et autres infos",
				"Everyone",
				"Informations : latence du bot, running time, websocket utilisé",
				{"" : ""}],
		"poll" : ["Crée un sondage, séparer les réponses par un ;",
				"Everyone",
				"",
				{"question" : "Question à poser dans le sondage",
				"réponses" : "Réponses possibles dans le sondage, séparer par ;",
				"salon o" : "Salon où envoyer le sondage"}],
		"role_react" : ["Configure une réaction sur un message et un rôle correspondant à donner",
				"Gérer les rôles",
				"`roles` et `message` n'ont pas besoin d'être renseignés tous les 2.\n\
Dans le cas où `message_id` est renseigné, un nouveau message avec le même contenu sera envoyé et l'original sera supprimé.\n\
Si échec suivi d'une possibilité `Actualiser`, choisir `Actualiser` et continuer normalement.",
				{"roles" : "Mentions des rôles à attribuer, avec ou sans séparation",
				"message o" : "Texte custom pour le message de role react, doit contenir les mentions de tous les rôles à attribuer",
				"message_id o" : "Identifiant d'un message à utiliser. ⚠ le message sera supprimé puis envoyé par le bot"}],
		"spam_emote" : ["Spamme une emote",
				"Everyone",
				"",
				{"emote o" : "Une emote qui va être spam pour atteindre la limite de 2000 caractères",
				"user o" : "Mentionne un utilisateur"}],
		"clear" : ["Nettoie un salon",
				"Gérer les Messages",
				"Préciser le nombre de messages et le salon (défaut : salon actuel), éventuellement l'auteur",
				{"nombre" : "Nombre de messages à chercher dans l'historique",
				"salon o" : "Salon où supprimer les messages",
				"user o" : "Ne supprimer que les messages de l'utilisateur en question"}],
		"ban" : ["Si tu sais pas ce que c'est, t'es pas concerné",
				"Ban",
				"",
				{"user" : "Utilisateur à bannir",
				"raison o" : "Motif du ban"}],
		"mute" : ["Mute une personne",
				"Mute",
				"Durée sous forme d'un nombre et d,j (jour), h (heure), m (minute), s (secondes), par défaut : 30m",
				{"user" : "Utilisateur à mute",
				"durée o" : "Durée du mute (defaut 30m)",
				"raison o" : "Motif du mute"}],
		"invite" : ["Affiche un lien pour inviter le bot",
				"Everyone",
				"",
				{"" : ""}],
		"code" : ["Envoie les fichiers du code source du bot",
				"Everyone",
				# ~ [texte](lien) -> syntaxe markdown, réservée aux bots dans le cas de discord
				f"""Doc Pycord : [ici]({docs['pycord']})
Portail des Développeurs : [ici]({docs['discord developpers']})
Doc Cron : [ici]({docs['crontab']}) et [là]({docs['cron']})""",
				{"" : ""}],
		"get_logs" : ["Envoie un ou plusieurs fichiers de logs",
				"Développeur",
				"",
				{"last_x_lines o" : "Les X dernières lignes de stderr"}],
		"qpup" : ["Lance le quiz Questions Pour Un Poulet !",
				"Everyone",
				"Tellement de lore derrière ce nom ...",
				{"nbquestions o" : "Nombre de questions désirées"}],
		"user_info" : ["Donne des informations sur la personne demandée",
				"Everyone",
				"",
				{"user" : "Utilisateur ciblé"}],
		"2048" : ["Démarre une partie de 2048",
				"Everyone",
				"",
				{"size o" : "Taille de la grille (défaut 4)"}],
		"suggestions" : ["Envoie un MP au dev à propos d'une suggestion que vous avez",
				"Everyone",
				"",
				{"" : ""}],
		"droprates" : ["Indique le nombre de conteneurs nécessaire pour une certaine probabilité de drop",
				"Everyone",
				"Renseigner le nom du conteneur et l'item voulu va afficher la fenêtre de résultats à tout le monde",
				{"pourcentage" : "Pourcentage de drop de l'item désiré",
				"nom o" : "Nom du conteneur",
				"item o" : "Item désiré"}],
		"clanships" : ["Actualise la liste des navires des joueurs d'un clan",
				"Everyone",
				"",
				{"clan" : "Tag du clan à actualiser"}],
		"compo" : ["Affiche les joueurs d'un possédant les ships définis comme étant la compo de ce clan",
				"Everyone",
				"Utiliser `/link_discord_wows` pour faire apparaître la mention discord au lieu du pseudo ingame",
				{"clan" : "Tag du clan à actualiser"}],
		"set_compo" : ["Définis une liste de navires comme étant la compo d'un clan",
				"Everyone",
				"",
				{"clan" : "Tag du clan dont la compo est définie",
				"ships" : "Liste des navires désirés, séparer par ;"}],
		"embed" : ["Crée un nouvel embed, entièrement customisable",
				"Everyone",
				"",
				{"edit" : "ID du message à éditer"}],
		"no_custom_messages" : ["Désactive les messages de réponses personnalisées sur ce serveur",
				"Administrateur",
				"Désactive tout, pour en remettre seulement certaines en service, envoyer un MP au bot",
				{"" : ""}]}
